; SPDX-License-Identifier: MIT
; Generated template is part of PrismQML, licensed under MIT.
; 生成模板是 PrismQML 的一部分，采用 MIT 许可证授权。
; Generated by prismqml-installer. DO NOT EDIT.
; Source manifest: prismqml-installer.json

#define PrismAppName "Gitora"
#define PrismAppVersion "1.7.0"
#define PrismAppPublisher "aki-riko"
#define PrismAppExe "Gitora.exe"
#define PrismAppUserModelID "PrismQML.Gitora"
#define PrismDistDir "build_dist\main_qml.dist"
#define PrismChineseMessagesFile "installer\ChineseSimplified.isl"
#define PrismAppURL "https://github.com/aki-riko/Gitora"
#define PrismSetupIcon "app\resource\images\logo.ico"

[Setup]
; A stable AppId makes every version upgrade the same installation. 固定 AppId 保证原位升级。
AppId={{8F3A9C2E-5B1D-4E7A-9C6F-A1B2C3D4E5F6}
AppName={#PrismAppName}
AppVersion={#PrismAppVersion}
AppPublisher={#PrismAppPublisher}
AppPublisherURL={#PrismAppURL}
AppSupportURL={#PrismAppURL}
AppUpdatesURL={#PrismAppURL}
DefaultDirName={autopf}\{#PrismAppName}
DefaultGroupName={#PrismAppName}
UsePreviousAppDir=yes
DisableProgramGroupPage=yes
OutputDir=dist_installer
OutputBaseFilename=Gitora-Setup-1.7.0
SetupIconFile={#PrismSetupIcon}
UninstallDisplayIcon={app}\{#PrismAppExe}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
ShowLanguageDialog=auto
LanguageDetectionMethod=uilanguage
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=admin
; Close old files; optional relaunch is handled once by [Run]. 关闭旧进程；可选重启由 [Run] 单次执行。
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "chinesesimplified"; MessagesFile: "{#PrismChineseMessagesFile}"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked


[Files]
Source: "{#PrismDistDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#PrismAppName}"; Filename: "{app}\{#PrismAppExe}"; IconFilename: "{app}\{#PrismAppExe}"; AppUserModelID: "{#PrismAppUserModelID}"
Name: "{group}\{cm:UninstallProgram,{#PrismAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#PrismAppName}"; Filename: "{app}\{#PrismAppExe}"; IconFilename: "{app}\{#PrismAppExe}"; AppUserModelID: "{#PrismAppUserModelID}"; Tasks: desktopicon

[Run]
; The manifest decides whether silent installs relaunch the installed application.
; 清单决定静默安装完成后是否重新启动已安装的应用。
Filename: "{app}\{#PrismAppExe}"; Description: "{cm:LaunchProgram,{#PrismAppName}}"; Flags: nowait postinstall
